### List all production items - JSON
GET http://127.0.0.1:8000/productions/
Accept: application/json
Content-Type: application/json

### List all production items - CSV
GET http://127.0.0.1:8000/productions/
Accept: text/csv
Content-Type: application/json

### List all production by product_id
GET http://127.0.0.1:8000/productions/?prod_id=1
Accept: application/json
Content-Type: application/json

### List all production by year
GET http://127.0.0.1:8000/productions/year/2024
Accept: application/json
Content-Type: application/json

### List all production by category
GET http://127.0.0.1:8000/productions/category/cat_branc
Accept: application/json
Content-Type: application/json

### List all production by year and category
GET http://127.0.0.1:8000/productions/category/cat_tint/year/2023
Accept: application/json
Content-Type: application/json

### Create new production item
POST http://127.0.0.1:8000/productions/
Accept: application/json
Content-Type: application/json

{
    "name": "Vinho Tinto 2017",
    "quantity": 100,
    "year": 2023,
    "category_id": 2
}